[package]
name = "bevy_space_invaders"
version = "0.1.0"
edition = "2021"

[lints.rust]
unsafe_code = "forbid"

[lints.clippy]
all = "warn"
correctness = "deny"
suspicious = "warn"
style = "warn"
complexity = "warn"
perf = "warn"
pedantic = "warn"
# restriction = "warn"
nursery = "warn"
# cargo = "warn"
needless_pass_by_value = "allow"

[dependencies]
bevy = { version = "0.12.1", features = ["dynamic_linking"] }
bevy-inspector-egui = "0.22.1"
bevy_mod_debugdump = "0.9.0"
bevy_screen_diagnostics = "0.4.0"
image = "0.24.8"
itertools = "0.12.0"
rand = "0.8.5"
winit = "0.28.7"


[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 3
